version: "3.2"
services:
  windit:
    environment:
      DB_HOST: postgres
    build:
      context: ./
      args:
        NODE_ENV: docker
    image: node:10.15.0-alpine
    command: /bin/sh -c "npm run serve"
    depends_on:
        - postgres
    volumes:
        - .:/usr/app
        - /usr/app/node_modules
    ports:
        - "3000:3000"
  postgres:
    image: postgres:11-alpine
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: windit
      POSTGRES_PASSWORD: windit
      POSTGRES_DB: windit
