postgres:
  image: postgres:11-alpine
  volumes:
    - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: windit
    POSTGRES_PASSWORD: windit
    POSTGRES_DB: windit