version: "3.2"
services:
  windit:
    build:
      context: ./
      args:
        NODE_ENV: development
    image: node:10.15.0-alpine
    command: /bin/sh -c "npm run serve"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
  postgres:
    image: postgres:11-alpine
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: windit
      POSTGRES_PASSWORD: windit
      POSTGRES_DB: windit
